version: '3.7'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
  app:
    build:
      args:
        - RAILS_ENV=development
        - RAILS_SECRET=foo
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  postgres_db: